# SPDX-FileCopyrightText: 2021 Maxwell G (@gotmax23)
# SPDX-License-Identifier: MIT
---
- name: Install ca-certificates
  # This is not included in tasks/main.yml, because it is not necessary to
  # download anything when just removing the package.
  ansible.builtin.package:
    name: ca-certificates

- name: Install Zoom (apt)
  when: ansible_pkg_mgr == "apt"
  block:
    # xz-utils is required to use the `apt` module's `deb` option.
    - name: Install xz-utils (apt)
      ansible.builtin.apt:
        name: xz-utils

    - name: Install Zoom (apt)
      ansible.builtin.apt:
        deb: "{{ zoom_deb_url }}"
        state: "{{ zoom_state }}"

- name: Install Zoom (rpm)
  when: zoom_rpm_url | length > 0
  ansible.builtin.package:
    name: "{{ zoom_rpm_url }}"

- name: Install Zoom (pacman)
  when: ansible_pkg_mgr == "pacman"
  block:
    - name: Download Zoom Pacman pkg
      ansible.builtin.get_url:
        url: "{{ zoom_pacman_pkg_url }}"
        dest: "{{ zoom_pacman_pkg_download_dest }}"
        mode: "0644"

    - name: Install Zoom Pacman pkg
      community.general.pacman:
        name: "{{ zoom_pacman_pkg_download_dest }}"
