# SPDX-FileCopyrightText: 2021 Maxwell G (@gotmax23)
# SPDX-License-Identifier: MIT
---
- name: Ensure variables are set correctly
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  connection: local
  become: false

- name: "{{ installw }} Zoom rpm key"
  when: zoom_rpm_url | length > 0
  ansible.builtin.rpm_key:
    key: "{{ zoom_rpm_key_url }}"
    fingerprint: "{{ zoom_rpm_key_fingerprint if zoom_check_rpm_key | bool else omit }}"
    state: "{{ zoom_state }}"

- name: Install Zoom
  when: zoom_state == "present"
  ansible.builtin.include_tasks: install.yml

# I had to seperate this task, because it is impossible to remove a package by a url;
# the actual package name is required.
- name: Uninstall Zoom
  when: zoom_state == "absent"
  ansible.builtin.package:
    name: zoom
    state: absent
